apiVersion: v1
kind: Service
metadata:
  name: credit-card-processing-service
  namespace: dev
  labels:
    app: credit-card-processing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: credit-card-processing
