apiVersion: v1
kind: Service
metadata:
  name: credit-card-processing-service
  namespace: dev
  labels:
    app: credit-card-processing
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: credit-card-processing
