name: Build and Test CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/helm/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'    
      - '**/helm/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Build with Maven
      run: mvn -B test

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_PASSWORD }}         
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.HUB_USERNAME }}/creditcardprocessing:$(git rev-parse --short HEAD)
    - name: Push the Docker image
      run: docker push ${{ secrets.HUB_USERNAME }}/creditcardprocessing:$(git rev-parse --short HEAD)
