name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_PASSWORD }}         
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.HUB_USERNAME }}/creditcardprocessing:latest
    - name: Push the Docker image
      run: docker push ${{ secrets.HUB_USERNAME }}/creditcardprocessing:latest
